ARG BASE_IMAGE=ghcr.io/kas-lab/suave-headless:latest
FROM $BASE_IMAGE

## Install TypeDB
RUN sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 17507562824cfdcc && \
    sudo gpg --export 17507562824cfdcc | sudo tee /etc/apt/trusted.gpg.d/vaticle.gpg > /dev/null && \
    echo "deb https://repo.typedb.com/public/public-release/deb/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/vaticle.list > /dev/null

RUN sudo apt-get update && sudo apt-get install -y \
    typedb=2.29.1 \
    && sudo rm -rf /var/lib/apt/lists/*

RUN pip3 install typedb-driver==2.29.7

COPY --chown=ubuntu-user:ubuntu-user suave_rosa/ $HOME/suave_ws/src/suave_rosa/suave_rosa/
COPY --chown=ubuntu-user:ubuntu-user suave_rosa_bt/ $HOME/suave_ws/src/suave_rosa/suave_rosa_bt/
COPY --chown=ubuntu-user:ubuntu-user suave_rosa_plansys/ $HOME/suave_ws/src/suave_rosa/suave_rosa_plansys/
COPY --chown=ubuntu-user:ubuntu-user suave_rosa_runner/ $HOME/suave_ws/src/suave_rosa/suave_rosa_runner/
COPY --chown=ubuntu-user:ubuntu-user suave_rosa.repos $HOME/suave_ws/suave_rosa.repos

WORKDIR $HOME/suave_ws
RUN wget https://raw.githubusercontent.com/kas-lab/suave/refs/heads/main/suave.repos
RUN vcs import src < suave.repos
RUN vcs import src < suave_rosa.repos

RUN ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash \
    && sudo apt update \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src -r -y"]

# Build suave
RUN ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install"]

RUN sudo apt autoremove -y && sudo rm -rf /var/lib/apt/lists/
